{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "embedded-postgresql.fullname" . }}
  labels:
    {{- include "embedded-postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "embedded-postgresql.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
