{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "embedded-rabbitmq.fullname" . }}
  labels:
    {{- include "embedded-rabbitmq.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  erlang-cookie: {{ .Values.auth.erlangCookie | quote }}
{{- end }}
