# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-nodes
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
data:
  nodes: {{ range $i, $e := until (int .Values.replicaCount) }}{{ if $i }},{{ end }}{{ $.Release.Name }}-typesense-{{ $i }}.ts.{{ $.Release.Namespace }}.svc.cluster.local:8107:8108{{ end }}
