{{- $replicaCount := int .Values.replicaCount -}}
{{- if gt $replicaCount 1 -}}
{{- $fullname := include "typesense.fullname" . -}}
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-nodes
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
data:
  nodes: {{ range $i, $_ := until $replicaCount -}}{{- if $i }},{{ end }}{{ $fullname }}-{{ $i }}.{{ $fullname }}.{{ $.Release.Namespace }}.svc.cluster.local:8107:8108{{- end }}
{{- end }}
