apiVersion: v1
kind: Service
metadata:
  name: ts
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8108
  selector:
    {{- include "typesense.selectorLabels" . | nindent 4 }}
